// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: Meteo-ESP32

#include "ui.h"

lv_obj_t * ui_Screen0;
lv_obj_t * ui_Screen0_Spinner1;
lv_obj_t * ui_Screen0_Label1;
lv_obj_t * ui_Screen0_Label2;

// event funtions

// build funtions

void ui_Screen0_screen_init(void)
{
    ui_Screen0 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen0_Spinner1 = lv_spinner_create(ui_Screen0);
    //lv_spinner_set_anim_params(ui_Screen0_Spinner1, 1000, 90);
    lv_obj_set_width(ui_Screen0_Spinner1, 100);
    lv_obj_set_height(ui_Screen0_Spinner1, 100);
    lv_obj_set_align(ui_Screen0_Spinner1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Screen0_Spinner1,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_Screen0_Spinner1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Screen0_Spinner1, lv_color_hex(0x5730A0), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Screen0_Spinner1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Screen0_Spinner1, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Screen0_Label1 = lv_label_create(ui_Screen0);
    lv_obj_set_width(ui_Screen0_Label1, 150);
    lv_obj_set_height(ui_Screen0_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen0_Label1, 0);
    lv_obj_set_y(ui_Screen0_Label1, -75);
    lv_obj_set_align(ui_Screen0_Label1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Screen0_Label1, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Screen0_Label1, "Initialization system...");
    lv_obj_set_style_text_font(ui_Screen0_Label1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen0_Label2 = lv_label_create(ui_Screen0);
    lv_obj_set_width(ui_Screen0_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen0_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen0_Label2, 0);
    lv_obj_set_y(ui_Screen0_Label2, 80);
    lv_obj_set_align(ui_Screen0_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen0_Label2, "Home \nmeteo station");
    lv_obj_set_style_text_color(ui_Screen0_Label2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen0_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Screen0_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen0_Label2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen0_screen_destroy(void)
{
    if(ui_Screen0) lv_obj_del(ui_Screen0);

    // NULL screen variables
    ui_Screen0 = NULL;
    ui_Screen0_Spinner1 = NULL;
    ui_Screen0_Label1 = NULL;
    ui_Screen0_Label2 = NULL;

}
