// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: Meteo-ESP32

#ifndef UI_SCREEN0_H
#define UI_SCREEN0_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen0
extern void ui_Screen0_screen_init(void);
extern void ui_Screen0_screen_destroy(void);
extern lv_obj_t * ui_Screen0;
extern lv_obj_t * ui_Screen0_Spinner1;
extern lv_obj_t * ui_Screen0_Label1;
extern lv_obj_t * ui_Screen0_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

