// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: Meteo-ESP32

#include "ui.h"

lv_obj_t * ui_Screen2;
lv_obj_t * ui_Screen2_Chart_CO2;
lv_obj_t * ui_Screen2_Chart_CO2_Xaxis;
lv_obj_t * ui_Screen2_Chart_CO2_Yaxis1;
lv_obj_t * ui_Screen2_Chart_CO2_Yaxis2;
lv_obj_t * ui_Screen2_Label_CO2;
lv_obj_t * ui_Screen2_Panel1;
lv_obj_t * ui_Screen2_Label_Header;
lv_obj_t * ui_Screen2_Label_CO2_Def;
lv_obj_t * ui_Screen2_Label_Prefix_Def;

// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen2_Chart_CO2 = lv_chart_create(ui_Screen2);
    lv_obj_set_width(ui_Screen2_Chart_CO2, 220);
    lv_obj_set_height(ui_Screen2_Chart_CO2, 150);
    lv_obj_set_align(ui_Screen2_Chart_CO2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen2_Chart_CO2, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_Screen2_Chart_CO2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_Screen2_Chart_CO2,
                    LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_Screen2_Chart_CO2, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_Screen2_Chart_CO2, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_Screen2_Chart_CO2, LV_CHART_AXIS_PRIMARY_Y, 50, 2000);
    lv_chart_set_div_line_count(ui_Screen2_Chart_CO2, 0, 0);
    lv_obj_set_style_radius(ui_Screen2_Chart_CO2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen2_Chart_CO2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2_Chart_CO2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen2_Chart_CO2, lv_color_hex(0x3AFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen2_Chart_CO2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Screen2_Chart_CO2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen2_Chart_CO2_Xaxis = lv_scale_create(ui_Screen2_Chart_CO2);
    lv_scale_set_mode(ui_Screen2_Chart_CO2_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_Screen2_Chart_CO2_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_Screen2_Chart_CO2_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_Screen2_Chart_CO2_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_Screen2_Chart_CO2,
                                                                              LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Screen2_Chart_CO2, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_Screen2_Chart_CO2_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Screen2_Chart_CO2_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_Screen2_Chart_CO2_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Screen2_Chart_CO2_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_Screen2_Chart_CO2_Xaxis, 10, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_Screen2_Chart_CO2_Xaxis, 0, 5 > 0 ? 5 - 1 : 0);
    lv_scale_set_total_tick_count(ui_Screen2_Chart_CO2_Xaxis, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Screen2_Chart_CO2_Xaxis, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_Screen2_Chart_CO2_Xaxis, false);
    ui_Screen2_Chart_CO2_Yaxis1 = lv_scale_create(ui_Screen2_Chart_CO2);
    lv_scale_set_mode(ui_Screen2_Chart_CO2_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_Screen2_Chart_CO2_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_Screen2_Chart_CO2_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Screen2_Chart_CO2_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_Screen2_Chart_CO2,
                                                                              LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Screen2_Chart_CO2, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_Screen2_Chart_CO2_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Screen2_Chart_CO2_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Screen2_Chart_CO2_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Screen2_Chart_CO2_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Screen2_Chart_CO2_Yaxis1, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_Screen2_Chart_CO2_Yaxis1,  50, 2000);
    lv_scale_set_total_tick_count(ui_Screen2_Chart_CO2_Yaxis1, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Screen2_Chart_CO2_Yaxis1, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_Screen2_Chart_CO2_Yaxis1, false);
    ui_Screen2_Chart_CO2_Yaxis2 = lv_scale_create(ui_Screen2_Chart_CO2);
    lv_scale_set_mode(ui_Screen2_Chart_CO2_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_Screen2_Chart_CO2_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_Screen2_Chart_CO2_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_Screen2_Chart_CO2_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Screen2_Chart_CO2,
                                                                              LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Screen2_Chart_CO2, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_Screen2_Chart_CO2_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Screen2_Chart_CO2_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Screen2_Chart_CO2_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Screen2_Chart_CO2_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Screen2_Chart_CO2_Yaxis2, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Screen2_Chart_CO2_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Screen2_Chart_CO2_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_Screen2_Chart_CO2_Yaxis2, false);

    lv_obj_set_style_line_color(ui_Screen2_Chart_CO2_Xaxis, lv_color_hex(0xC0C0C0), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Screen2_Chart_CO2_Xaxis, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_Screen2_Chart_CO2_Yaxis1, lv_color_hex(0xC0C0C0), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Screen2_Chart_CO2_Yaxis1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_Screen2_Chart_CO2_Yaxis2, lv_color_hex(0xC0C0C0), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Screen2_Chart_CO2_Yaxis2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_Screen2_Chart_CO2_Xaxis, lv_color_hex(0xC0C0C0), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Screen2_Chart_CO2_Xaxis, 0, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_Screen2_Chart_CO2_Yaxis1, lv_color_hex(0xC0C0C0), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Screen2_Chart_CO2_Yaxis1, 0, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_Screen2_Chart_CO2_Yaxis2, lv_color_hex(0xC0C0C0), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Screen2_Chart_CO2_Yaxis2, 0, LV_PART_ITEMS | LV_STATE_DEFAULT);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_Screen2_Chart_CO2, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_Screen2_Chart_CO2, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_Screen2_Label_CO2 = lv_label_create(ui_Screen2_Chart_CO2);
    lv_obj_set_width(ui_Screen2_Label_CO2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen2_Label_CO2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen2_Label_CO2, 0);
    lv_obj_set_y(ui_Screen2_Label_CO2, 15);
    lv_label_set_text(ui_Screen2_Label_CO2, "400");
    lv_obj_set_style_text_color(ui_Screen2_Label_CO2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen2_Label_CO2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen2_Label_CO2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen2_Panel1 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Screen2_Panel1, 120);
    lv_obj_set_height(ui_Screen2_Panel1, 50);
    lv_obj_set_x(ui_Screen2_Panel1, 0);
    lv_obj_set_y(ui_Screen2_Panel1, -110);
    lv_obj_set_align(ui_Screen2_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Screen2_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen2_Panel1, 5000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen2_Panel1, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen2_Label_Header = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Screen2_Label_Header, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen2_Label_Header, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen2_Label_Header, 0);
    lv_obj_set_y(ui_Screen2_Label_Header, -100);
    lv_obj_set_align(ui_Screen2_Label_Header, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen2_Label_Header, "CO2");
    lv_obj_set_style_text_font(ui_Screen2_Label_Header, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen2_Label_CO2_Def = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Screen2_Label_CO2_Def, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen2_Label_CO2_Def, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen2_Label_CO2_Def, -50);
    lv_obj_set_y(ui_Screen2_Label_CO2_Def, -65);
    lv_obj_set_align(ui_Screen2_Label_CO2_Def, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen2_Label_CO2_Def, "400");
    lv_obj_add_flag(ui_Screen2_Label_CO2_Def, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Screen2_Label_CO2_Def, lv_color_hex(0xDB3E1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen2_Label_CO2_Def, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen2_Label_CO2_Def, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen2_Label_Prefix_Def = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Screen2_Label_Prefix_Def, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen2_Label_Prefix_Def, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen2_Label_Prefix_Def, 5);
    lv_obj_set_y(ui_Screen2_Label_Prefix_Def, -65);
    lv_obj_set_align(ui_Screen2_Label_Prefix_Def, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen2_Label_Prefix_Def, "[ppm]");
    lv_obj_add_flag(ui_Screen2_Label_Prefix_Def, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Screen2_Label_Prefix_Def, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen2_Label_Prefix_Def, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen2_Label_Prefix_Def, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Screen2_Chart_CO2 = NULL;
    ui_Screen2_Label_CO2 = NULL;
    ui_Screen2_Panel1 = NULL;
    ui_Screen2_Label_Header = NULL;
    ui_Screen2_Label_CO2_Def = NULL;
    ui_Screen2_Label_Prefix_Def = NULL;

}
