// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: Meteo-ESP32

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Screen1_Arc_CO2;
extern lv_obj_t * ui_Screen1_Arc_Temp;
extern lv_obj_t * ui_Screen1_Arc_Hum;
extern lv_obj_t * ui_Screen1_Arc_Battery;
extern lv_obj_t * ui_Screen1_Container_CO2;
extern lv_obj_t * ui_Screen1_Label_CO2;
extern lv_obj_t * ui_Screen1_Label_Prefix_CO2_;
extern lv_obj_t * ui_Screen1_Container_Hum;
extern lv_obj_t * ui_Screen1_Label_Hum;
extern lv_obj_t * ui_Screen1_Label_Prefix_Hum;
extern lv_obj_t * ui_Screen1_Container_Temp;
extern lv_obj_t * ui_Screen1_Label_Temp;
extern lv_obj_t * ui_Screen1_Label_Prefix_Temp;
extern lv_obj_t * ui_Screen1_Container_TVOC;
extern lv_obj_t * ui_Screen1_Label_TVOC;
extern lv_obj_t * ui_Screen1_Label_Prefix_TVOC;
extern lv_obj_t * ui_Screen1_Container_Press;
extern lv_obj_t * ui_Screen1_Label_Press;
extern lv_obj_t * ui_Screen1_Label_Prefix_Press;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

