// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: Meteo-ESP32

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Screen2_Chart_CO2;
extern lv_obj_t * ui_Screen2_Chart_CO2_Xaxis;
extern lv_obj_t * ui_Screen2_Chart_CO2_Yaxis1;
extern lv_obj_t * ui_Screen2_Chart_CO2_Yaxis2;
extern lv_obj_t * ui_Screen2_Panel1;
extern lv_obj_t * ui_Screen2_Label_CO2;
extern lv_obj_t * ui_Screen2_Label_Header;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

