// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: Meteo_Project

#include "ui.h"

lv_obj_t * ui_Screen1;
lv_obj_t * ui_Screen1_Arc_Temp;
lv_obj_t * ui_Screen1_Arc_Hum;
lv_obj_t * ui_Screen1_Arc_Press;
lv_obj_t * ui_Screen1_Label1;
lv_obj_t * ui_Screen1_Label2;
lv_obj_t * ui_Screen1_Label3;
lv_obj_t * ui_Screen1_Label_Temp;
lv_obj_t * ui_Screen1_Label_Hum;
lv_obj_t * ui_Screen1_Label_Press;

// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_Arc_Temp = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Arc_Temp, 230);
    lv_obj_set_height(ui_Screen1_Arc_Temp, 230);
    lv_obj_set_align(ui_Screen1_Arc_Temp, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Screen1_Arc_Temp, 0, 50);
    lv_arc_set_value(ui_Screen1_Arc_Temp, 25);
    lv_arc_set_bg_angles(ui_Screen1_Arc_Temp, 270, 180);
    lv_obj_set_style_arc_width(ui_Screen1_Arc_Temp, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Screen1_Arc_Temp, lv_color_hex(0xFFF80B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Screen1_Arc_Temp, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen1_Arc_Temp, lv_color_hex(0xFFF80B), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Arc_Temp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Screen1_Arc_Temp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Screen1_Arc_Temp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Screen1_Arc_Temp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Screen1_Arc_Temp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Screen1_Arc_Hum = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Arc_Hum, 195);
    lv_obj_set_height(ui_Screen1_Arc_Hum, 195);
    lv_obj_set_align(ui_Screen1_Arc_Hum, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Screen1_Arc_Hum, 33);
    lv_arc_set_bg_angles(ui_Screen1_Arc_Hum, 270, 180);
    lv_obj_set_style_arc_width(ui_Screen1_Arc_Hum, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Screen1_Arc_Hum, lv_color_hex(0x0B62FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Screen1_Arc_Hum, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen1_Arc_Hum, lv_color_hex(0x0B62FF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Arc_Hum, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Screen1_Arc_Hum, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Screen1_Arc_Hum, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Screen1_Arc_Hum, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Screen1_Arc_Hum, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Screen1_Arc_Press = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Arc_Press, 160);
    lv_obj_set_height(ui_Screen1_Arc_Press, 160);
    lv_obj_set_align(ui_Screen1_Arc_Press, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Screen1_Arc_Press, 0, 1000);
    lv_arc_set_value(ui_Screen1_Arc_Press, 745);
    lv_arc_set_bg_angles(ui_Screen1_Arc_Press, 270, 180);
    lv_obj_set_style_pad_left(ui_Screen1_Arc_Press, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Screen1_Arc_Press, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Screen1_Arc_Press, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Screen1_Arc_Press, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Screen1_Arc_Press, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Screen1_Arc_Press, lv_color_hex(0x1EFF19), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Screen1_Arc_Press, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen1_Arc_Press, lv_color_hex(0x1EFF19), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Arc_Press, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Screen1_Arc_Press, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Screen1_Arc_Press, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Screen1_Arc_Press, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Screen1_Arc_Press, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Screen1_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label1, 0);
    lv_obj_set_y(ui_Screen1_Label1, -50);
    lv_obj_set_align(ui_Screen1_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label1, "Temp");
    lv_obj_set_style_text_color(ui_Screen1_Label1, lv_color_hex(0xFFFA08), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_Label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label2, 0);
    lv_obj_set_y(ui_Screen1_Label2, -10);
    lv_obj_set_align(ui_Screen1_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label2, "Hum");
    lv_obj_set_style_text_color(ui_Screen1_Label2, lv_color_hex(0x0B62FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_Label2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label3, 0);
    lv_obj_set_y(ui_Screen1_Label3, 30);
    lv_obj_set_align(ui_Screen1_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label3, "Press");
    lv_obj_set_style_text_color(ui_Screen1_Label3, lv_color_hex(0x1EFF19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_Label3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label_Temp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Label_Temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label_Temp, 0);
    lv_obj_set_y(ui_Screen1_Label_Temp, -30);
    lv_obj_set_align(ui_Screen1_Label_Temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label_Temp, "0");
    lv_obj_set_style_text_font(ui_Screen1_Label_Temp, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label_Hum = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Label_Hum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_Hum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label_Hum, 0);
    lv_obj_set_y(ui_Screen1_Label_Hum, 10);
    lv_obj_set_align(ui_Screen1_Label_Hum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label_Hum, "0");
    lv_obj_set_style_text_font(ui_Screen1_Label_Hum, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label_Press = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Label_Press, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_Press, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label_Press, 0);
    lv_obj_set_y(ui_Screen1_Label_Press, 50);
    lv_obj_set_align(ui_Screen1_Label_Press, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label_Press, "0");
    lv_obj_set_style_text_font(ui_Screen1_Label_Press, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Screen1_Arc_Temp = NULL;
    ui_Screen1_Arc_Hum = NULL;
    ui_Screen1_Arc_Press = NULL;
    ui_Screen1_Label1 = NULL;
    ui_Screen1_Label2 = NULL;
    ui_Screen1_Label3 = NULL;
    ui_Screen1_Label_Temp = NULL;
    ui_Screen1_Label_Hum = NULL;
    ui_Screen1_Label_Press = NULL;

}
