// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: Meteo-ESP32

#include "ui.h"

lv_obj_t * ui_Screen3;
lv_obj_t * ui_Screen3_Arc_CO2;
lv_obj_t * ui_Screen3_Arc_Temp;
lv_obj_t * ui_Screen3_Arc_Hum;
lv_obj_t * ui_Screen3_Arc_Battery;
lv_obj_t * ui_Screen3_Label_Temp_Def;
lv_obj_t * ui_Screen3_Label_Temp1;
lv_obj_t * ui_Screen3_Label_Hum_Def;
lv_obj_t * ui_Screen3_Label_CO2_Def;
lv_obj_t * ui_Screen3_Label_Temp;
lv_obj_t * ui_Screen3_Label1;
lv_obj_t * ui_Screen3_Label_Press;
lv_obj_t * ui_Screen3_Label6;
lv_obj_t * ui_Screen3_Label_Hum;
lv_obj_t * ui_Screen3_Label3;
lv_obj_t * ui_Screen3_Label_CO2;
lv_obj_t * ui_Screen3_Label4;
lv_obj_t * ui_Screen3_Label_Temp_Second;
lv_obj_t * ui_Screen3_Label5;
lv_obj_t * ui_Screen3_Label_Hour;
lv_obj_t * ui_Screen3_Label_Minute;

// event funtions

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen3_Arc_CO2 = lv_arc_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3_Arc_CO2, 230);
    lv_obj_set_height(ui_Screen3_Arc_CO2, 230);
    lv_obj_set_align(ui_Screen3_Arc_CO2, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Screen3_Arc_CO2, 380, 2500);
    lv_arc_set_value(ui_Screen3_Arc_CO2, 1200);
    lv_arc_set_bg_angles(ui_Screen3_Arc_CO2, 94, 270);
    lv_obj_set_style_arc_width(ui_Screen3_Arc_CO2, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Screen3_Arc_CO2, lv_color_hex(0xDE3C18), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Screen3_Arc_CO2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen3_Arc_CO2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Arc_CO2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Screen3_Arc_Temp = lv_arc_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3_Arc_Temp, 180);
    lv_obj_set_height(ui_Screen3_Arc_Temp, 180);
    lv_obj_set_align(ui_Screen3_Arc_Temp, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Screen3_Arc_Temp, 0, 35);
    lv_arc_set_value(ui_Screen3_Arc_Temp, 20);
    lv_arc_set_bg_angles(ui_Screen3_Arc_Temp, 0, 180);
    lv_obj_set_style_arc_width(ui_Screen3_Arc_Temp, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Screen3_Arc_Temp, lv_color_hex(0xEFB800), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Screen3_Arc_Temp, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen3_Arc_Temp, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Arc_Temp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Screen3_Arc_Hum = lv_arc_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3_Arc_Hum, 130);
    lv_obj_set_height(ui_Screen3_Arc_Hum, 130);
    lv_obj_set_align(ui_Screen3_Arc_Hum, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Screen3_Arc_Hum, 50);
    lv_arc_set_bg_angles(ui_Screen3_Arc_Hum, 90, 180);
    lv_obj_set_style_arc_width(ui_Screen3_Arc_Hum, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Screen3_Arc_Hum, lv_color_hex(0x00DB96), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Screen3_Arc_Hum, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen3_Arc_Hum, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Arc_Hum, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Screen3_Arc_Battery = lv_arc_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3_Arc_Battery, 230);
    lv_obj_set_height(ui_Screen3_Arc_Battery, 230);
    lv_obj_set_align(ui_Screen3_Arc_Battery, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Screen3_Arc_Battery, 50);
    lv_arc_set_bg_angles(ui_Screen3_Arc_Battery, 0, 86);
    lv_obj_set_style_arc_width(ui_Screen3_Arc_Battery, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Screen3_Arc_Battery, lv_color_hex(0x212160), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Screen3_Arc_Battery, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen3_Arc_Battery, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3_Arc_Battery, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Screen3_Label_Temp_Def = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3_Label_Temp_Def, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label_Temp_Def, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label_Temp_Def, 81);
    lv_obj_set_y(ui_Screen3_Label_Temp_Def, -20);
    lv_obj_set_align(ui_Screen3_Label_Temp_Def, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label_Temp_Def, "22.5°");
    lv_obj_add_flag(ui_Screen3_Label_Temp_Def, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Screen3_Label_Temp_Def, lv_color_hex(0xEFB800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label_Temp_Def, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen3_Label_Temp_Def, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label_Temp1 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3_Label_Temp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label_Temp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label_Temp1, 74);
    lv_obj_set_y(ui_Screen3_Label_Temp1, 95);
    lv_obj_set_align(ui_Screen3_Label_Temp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label_Temp1, "22.5°");
    lv_obj_add_flag(ui_Screen3_Label_Temp1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Screen3_Label_Temp1, lv_color_hex(0xEFB800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label_Temp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen3_Label_Temp1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_Screen3_Label_Temp1, -450, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label_Hum_Def = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3_Label_Hum_Def, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label_Hum_Def, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label_Hum_Def, -56);
    lv_obj_set_y(ui_Screen3_Label_Hum_Def, -20);
    lv_obj_set_align(ui_Screen3_Label_Hum_Def, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label_Hum_Def, "50%");
    lv_obj_add_flag(ui_Screen3_Label_Hum_Def, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Screen3_Label_Hum_Def, lv_color_hex(0x00DB96), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label_Hum_Def, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen3_Label_Hum_Def, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label_CO2_Def = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3_Label_CO2_Def, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label_CO2_Def, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label_CO2_Def, 0);
    lv_obj_set_y(ui_Screen3_Label_CO2_Def, -75);
    lv_obj_set_align(ui_Screen3_Label_CO2_Def, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label_CO2_Def, "1200ppm");
    lv_obj_add_flag(ui_Screen3_Label_CO2_Def, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Screen3_Label_CO2_Def, lv_color_hex(0xF500E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label_CO2_Def, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen3_Label_CO2_Def, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label_Temp = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3_Label_Temp, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Screen3_Label_Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label_Temp, 80);
    lv_obj_set_y(ui_Screen3_Label_Temp, -18);
    lv_obj_set_align(ui_Screen3_Label_Temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label_Temp, "23.5");
    lv_obj_remove_flag(ui_Screen3_Label_Temp,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Screen3_Label_Temp, lv_color_hex(0xEEBA00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label_Temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen3_Label_Temp, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label1 = lv_label_create(ui_Screen3_Label_Temp);
    lv_obj_set_width(ui_Screen3_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label1, 47);
    lv_obj_set_y(ui_Screen3_Label1, -10);
    lv_obj_set_align(ui_Screen3_Label1, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Screen3_Label1, "0");
    lv_obj_set_style_text_color(ui_Screen3_Label1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen3_Label1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label_Press = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3_Label_Press, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Screen3_Label_Press, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label_Press, 15);
    lv_obj_set_y(ui_Screen3_Label_Press, 31);
    lv_obj_set_align(ui_Screen3_Label_Press, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label_Press, "758");
    lv_obj_remove_flag(ui_Screen3_Label_Press,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Screen3_Label_Press, lv_color_hex(0x009A69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label_Press, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen3_Label_Press, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label6 = lv_label_create(ui_Screen3_Label_Press);
    lv_obj_set_width(ui_Screen3_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label6, 32);
    lv_obj_set_y(ui_Screen3_Label6, 0);
    lv_obj_set_align(ui_Screen3_Label6, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Screen3_Label6, "mmHg");
    lv_obj_set_style_text_color(ui_Screen3_Label6, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen3_Label6, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label_Hum = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3_Label_Hum, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Screen3_Label_Hum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label_Hum, -57);
    lv_obj_set_y(ui_Screen3_Label_Hum, -18);
    lv_obj_set_align(ui_Screen3_Label_Hum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label_Hum, "50");
    lv_obj_remove_flag(ui_Screen3_Label_Hum,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Screen3_Label_Hum, lv_color_hex(0x00DB96), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label_Hum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen3_Label_Hum, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label3 = lv_label_create(ui_Screen3_Label_Hum);
    lv_obj_set_width(ui_Screen3_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label3, 31);
    lv_obj_set_y(ui_Screen3_Label3, -2);
    lv_obj_set_align(ui_Screen3_Label3, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Screen3_Label3, "%");
    lv_obj_set_style_text_color(ui_Screen3_Label3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen3_Label3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label_CO2 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3_Label_CO2, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Screen3_Label_CO2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label_CO2, 20);
    lv_obj_set_y(ui_Screen3_Label_CO2, -90);
    lv_obj_set_align(ui_Screen3_Label_CO2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label_CO2, "1200");
    lv_obj_remove_flag(ui_Screen3_Label_CO2,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Screen3_Label_CO2, lv_color_hex(0xDE3C18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label_CO2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen3_Label_CO2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label4 = lv_label_create(ui_Screen3_Label_CO2);
    lv_obj_set_width(ui_Screen3_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label4, 55);
    lv_obj_set_y(ui_Screen3_Label4, 0);
    lv_obj_set_align(ui_Screen3_Label4, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Screen3_Label4, "ppm");
    lv_obj_set_style_text_color(ui_Screen3_Label4, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen3_Label4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label_Temp_Second = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3_Label_Temp_Second, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Screen3_Label_Temp_Second, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label_Temp_Second, 73);
    lv_obj_set_y(ui_Screen3_Label_Temp_Second, 95);
    lv_obj_set_align(ui_Screen3_Label_Temp_Second, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label_Temp_Second, "22.5");
    lv_obj_add_flag(ui_Screen3_Label_Temp_Second, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Screen3_Label_Temp_Second,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Screen3_Label_Temp_Second, lv_color_hex(0xEEBA00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label_Temp_Second, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen3_Label_Temp_Second, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_Screen3_Label_Temp_Second, -450, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label5 = lv_label_create(ui_Screen3_Label_Temp_Second);
    lv_obj_set_width(ui_Screen3_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label5, 47);
    lv_obj_set_y(ui_Screen3_Label5, -10);
    lv_obj_set_align(ui_Screen3_Label5, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Screen3_Label5, "0");
    lv_obj_set_style_text_color(ui_Screen3_Label5, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen3_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen3_Label5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label_Hour = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3_Label_Hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label_Hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label_Hour, 10);
    lv_obj_set_y(ui_Screen3_Label_Hour, -36);
    lv_obj_set_align(ui_Screen3_Label_Hour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Label_Hour, "12");
    lv_obj_add_flag(ui_Screen3_Label_Hour, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_Screen3_Label_Hour, &ui_font_Font_19280_60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Label_Minute = lv_label_create(ui_Screen3_Label_Hour);
    lv_obj_set_width(ui_Screen3_Label_Minute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Label_Minute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Label_Minute, 60);
    lv_obj_set_y(ui_Screen3_Label_Minute, -35);
    lv_obj_set_align(ui_Screen3_Label_Minute, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Screen3_Label_Minute, "10");
    lv_obj_set_style_text_font(ui_Screen3_Label_Minute, &ui_font_Font_19280_24, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Screen3_Arc_CO2 = NULL;
    ui_Screen3_Arc_Temp = NULL;
    ui_Screen3_Arc_Hum = NULL;
    ui_Screen3_Arc_Battery = NULL;
    ui_Screen3_Label_Temp_Def = NULL;
    ui_Screen3_Label_Temp1 = NULL;
    ui_Screen3_Label_Hum_Def = NULL;
    ui_Screen3_Label_CO2_Def = NULL;
    ui_Screen3_Label_Temp = NULL;
    ui_Screen3_Label1 = NULL;
    ui_Screen3_Label_Press = NULL;
    ui_Screen3_Label6 = NULL;
    ui_Screen3_Label_Hum = NULL;
    ui_Screen3_Label3 = NULL;
    ui_Screen3_Label_CO2 = NULL;
    ui_Screen3_Label4 = NULL;
    ui_Screen3_Label_Temp_Second = NULL;
    ui_Screen3_Label5 = NULL;
    ui_Screen3_Label_Hour = NULL;
    ui_Screen3_Label_Minute = NULL;

}
